import type { LobbyRole } from "@/types/lobby";

export const DEFAULT_CHAMPION_AVATAR = "/champion/Ahri.png";
export const DEFAULT_SUMMONER_AVATAR = "/profileicon/0.png";
export const DEFAULT_AVATAR = DEFAULT_CHAMPION_AVATAR;

export const PROFILE_ICONS = [
  "/profileicon/0.png",
  "/profileicon/1.png",
  "/profileicon/2.png",
  "/profileicon/3.png",
  "/profileicon/4.png",
  "/profileicon/5.png",
  "/profileicon/6.png",
  "/profileicon/7.png",
  "/profileicon/8.png",
  "/profileicon/9.png",
  "/profileicon/10.png",
  "/profileicon/11.png",
  "/profileicon/12.png",
  "/profileicon/14.png",
  "/profileicon/15.png",
  "/profileicon/18.png",
  "/profileicon/19.png",
  "/profileicon/20.png",
  "/profileicon/21.png",
  "/profileicon/22.png",
  "/profileicon/23.png",
  "/profileicon/24.png",
  "/profileicon/25.png",
  "/profileicon/26.png",
  "/profileicon/28.png",
  "/profileicon/29.png",
] as const;

export const CHAMPION_AVATARS = [
  "/champion/Aatrox.png",
  "/champion/Ahri.png",
  "/champion/Akali.png",
  "/champion/Akshan.png",
  "/champion/Alistar.png",
  "/champion/Ambessa.png",
  "/champion/Amumu.png",
  "/champion/Anivia.png",
  "/champion/Annie.png",
  "/champion/Aphelios.png",
  "/champion/Ashe.png",
  "/champion/AurelionSol.png",
  "/champion/Aurora.png",
  "/champion/Azir.png",
  "/champion/Bard.png",
  "/champion/Belveth.png",
  "/champion/Blitzcrank.png",
  "/champion/Brand.png",
  "/champion/Braum.png",
  "/champion/Briar.png",
  "/champion/Caitlyn.png",
  "/champion/Camille.png",
  "/champion/Cassiopeia.png",
  "/champion/Chogath.png",
  "/champion/Corki.png",
  "/champion/Darius.png",
  "/champion/Diana.png",
  "/champion/Draven.png",
  "/champion/DrMundo.png",
  "/champion/Ekko.png",
  "/champion/Elise.png",
  "/champion/Evelynn.png",
  "/champion/Ezreal.png",
  "/champion/Fiddlesticks.png",
  "/champion/Fiora.png",
  "/champion/Fizz.png",
  "/champion/Galio.png",
  "/champion/Gangplank.png",
  "/champion/Garen.png",
  "/champion/Gnar.png",
  "/champion/Gragas.png",
  "/champion/Graves.png",
  "/champion/Gwen.png",
  "/champion/Hecarim.png",
  "/champion/Heimerdinger.png",
  "/champion/Hwei.png",
  "/champion/Illaoi.png",
  "/champion/Irelia.png",
  "/champion/Ivern.png",
  "/champion/Janna.png",
  "/champion/JarvanIV.png",
  "/champion/Jax.png",
  "/champion/Jayce.png",
  "/champion/Jhin.png",
  "/champion/Jinx.png",
  "/champion/Kaisa.png",
  "/champion/Kalista.png",
  "/champion/Karma.png",
  "/champion/Karthus.png",
  "/champion/Kassadin.png",
  "/champion/Katarina.png",
  "/champion/Kayle.png",
  "/champion/Kayn.png",
  "/champion/Kennen.png",
  "/champion/Khazix.png",
  "/champion/Kindred.png",
  "/champion/Kled.png",
  "/champion/KogMaw.png",
  "/champion/KSante.png",
  "/champion/Leblanc.png",
  "/champion/LeeSin.png",
  "/champion/Leona.png",
  "/champion/Lillia.png",
  "/champion/Lissandra.png",
  "/champion/Lucian.png",
  "/champion/Lulu.png",
  "/champion/Lux.png",
  "/champion/Malphite.png",
  "/champion/Malzahar.png",
  "/champion/Maokai.png",
  "/champion/MasterYi.png",
  "/champion/Mel.png",
  "/champion/Milio.png",
  "/champion/MissFortune.png",
  "/champion/MonkeyKing.png",
  "/champion/Mordekaiser.png",
  "/champion/Morgana.png",
  "/champion/Naafiri.png",
  "/champion/Nami.png",
  "/champion/Nasus.png",
  "/champion/Nautilus.png",
  "/champion/Neeko.png",
  "/champion/Nidalee.png",
  "/champion/Nilah.png",
  "/champion/Nocturne.png",
  "/champion/Nunu.png",
  "/champion/Olaf.png",
  "/champion/Orianna.png",
  "/champion/Ornn.png",
  "/champion/Pantheon.png",
  "/champion/Poppy.png",
  "/champion/Pyke.png",
  "/champion/Qiyana.png",
  "/champion/Quinn.png",
  "/champion/Rakan.png",
  "/champion/Rammus.png",
  "/champion/RekSai.png",
  "/champion/Rell.png",
  "/champion/Renata.png",
  "/champion/Renekton.png",
  "/champion/Rengar.png",
  "/champion/Riven.png",
  "/champion/Rumble.png",
  "/champion/Ryze.png",
  "/champion/Samira.png",
  "/champion/Sejuani.png",
  "/champion/Senna.png",
  "/champion/Seraphine.png",
  "/champion/Sett.png",
  "/champion/Shaco.png",
  "/champion/Shen.png",
  "/champion/Shyvana.png",
  "/champion/Singed.png",
  "/champion/Sion.png",
  "/champion/Sivir.png",
  "/champion/Skarner.png",
  "/champion/Smolder.png",
  "/champion/Sona.png",
  "/champion/Soraka.png",
  "/champion/Swain.png",
  "/champion/Sylas.png",
  "/champion/Syndra.png",
  "/champion/TahmKench.png",
  "/champion/Taliyah.png",
  "/champion/Talon.png",
  "/champion/Taric.png",
  "/champion/Teemo.png",
  "/champion/Thresh.png",
  "/champion/Tristana.png",
  "/champion/Trundle.png",
  "/champion/Tryndamere.png",
  "/champion/TwistedFate.png",
  "/champion/Twitch.png",
  "/champion/Udyr.png",
  "/champion/Urgot.png",
  "/champion/Varus.png",
  "/champion/Vayne.png",
  "/champion/Veigar.png",
  "/champion/Velkoz.png",
  "/champion/Vex.png",
  "/champion/Vi.png",
  "/champion/Viego.png",
  "/champion/Viktor.png",
  "/champion/Vladimir.png",
  "/champion/Volibear.png",
  "/champion/Warwick.png",
  "/champion/Xayah.png",
  "/champion/Xerath.png",
  "/champion/XinZhao.png",
  "/champion/Yasuo.png",
  "/champion/Yone.png",
  "/champion/Yorick.png",
  "/champion/Yunara.png",
  "/champion/Yuumi.png",
  "/champion/Zaahen.png",
  "/champion/Zac.png",
  "/champion/Zed.png",
  "/champion/Zeri.png",
  "/champion/Ziggs.png",
  "/champion/Zilean.png",
  "/champion/Zoe.png",
  "/champion/Zyra.png",
] as const;

export function getDefaultAvatarForRole(role: LobbyRole | undefined | null) {
  return role === "summoner"
    ? DEFAULT_SUMMONER_AVATAR
    : DEFAULT_CHAMPION_AVATAR;
}

export function getAvatarOptionsForRole(role: LobbyRole | undefined | null) {
  return role === "summoner" ? PROFILE_ICONS : CHAMPION_AVATARS;
}

export function isAvatarValidForRole(
  avatar: string | null | undefined,
  role: LobbyRole | undefined | null,
) {
  if (!avatar) {
    return false;
  }

  const options = getAvatarOptionsForRole(role);
  return (options as readonly string[]).includes(avatar);
}
